FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UPSTREAM_BASE_URL=http://127.0.0.1:8000
ENV UPSTREAM_MODEL=vl-model
ENV REQUEST_TIMEOUT=120
ENV DROP_UNSUPPORTED_PARAMS=true
ENV STRIP_REASONING=true
ENV DISABLE_UPSTREAM_THINKING=true
ENV LAYOUT_MAX_TOKENS=1024
ENV TEXT_MAX_TOKENS=2048
ENV TABLE_MAX_TOKENS=2048
ENV FORMULA_MAX_TOKENS=512
ENV IMAGE_MAX_TOKENS=1024
ENV LAYOUT_MAX_IMAGE_SIDE=896
ENV ADAPTER_CACHE_SIZE=256
ENV ADAPTER_CACHE_TTL_SECONDS=3600
ENV ADAPTER_COALESCE_REQUESTS=true
ENV AUTO_TEXT_PDF_ROUTING=true
ENV TEXT_PDF_BACKEND=pipeline
ENV TEXT_PDF_MIN_CHARS=120
ENV TEXT_PDF_SCAN_PAGES=3

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src

RUN python -m pip install --no-cache-dir --upgrade pip \
    && python -m pip install --no-cache-dir .

EXPOSE 18000 8000

CMD ["python", "-m", "uvicorn", "mineru_adapter.api:app", "--host", "0.0.0.0", "--port", "18000"]
